name: .NET Core 3.1
on:
  push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:
  BuildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'
    - uses: cryptic-wizard/run-specflow-tests@v1.3.1
      with:
        test-assembly-path: RandomWordGeneratorTest/bin/Release/netcoreapp3.1
        test-assembly-dll: RandomWordGeneratorTest.dll
        output-html: RandomWordGeneratorResults.html
        framework: netcoreapp3.1
        logger: trx
        logger-file-name: ../../RandomWordGeneratorResults.trx
    - uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Specflow Tests
        path: RandomWordGeneratorResults.trx
        reporter: dotnet-trx