name: .NET Core

on:
  push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup .NET Core Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build Project
      run: dotnet build --no-restore
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    - name: Generate Timestamp
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: -5
        format: 'YYYY-MM-DD-HH-mm-ss'
    - name: Generate Specflow Test Report
      env:
        TEST_RESULTS_PATH: "NameGeneratorTest/bin/Debug/netcoreapp3.1"
        TIME: "${{ steps.time.outputs.time }}"
      run: |
        dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
        livingdoc test-assembly ${TEST_RESULTS_PATH}/NameGeneratorTest.dll -t ${TEST_RESULTS_PATH}/TestExecution.json
        #mv LivingDoc.html TestReport_${TIME}.html --verbose //Rename is successful but the artifact does not exist
    - name: Publish Specflow Test Report
      uses: actions/upload-artifact@v2
      with:
        name: TestReport_${TIME}
        path: LivingDoc.html
