name: .NET Core

on:
  push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup .NET Core Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build Project
      run: dotnet build --no-restore
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    - name: Generate Specflow Test Report
      env:
        TEST_RESULTS_PATH: "RandomWordGeneratorTest/bin/Debug/netcoreapp3.1"
      run: |
        dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
        livingdoc test-assembly ${TEST_RESULTS_PATH}/RandomWordGeneratorTest.dll -t ${TEST_RESULTS_PATH}/TestExecution.json
    - name: Publish Specflow Test Report
      uses: actions/upload-artifact@v2
      with:
        name: RandomWordGeneratorTestReport
        path: LivingDoc.html