name: .NET Core

on:
  push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup .NET Core Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build Project
      run: dotnet build --no-restore
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
      env:
        FILEPATH: "NameGeneratorTest/bin/Debug/netcoreapp3.1"

    - name: Generate Specflow Test Report
      run: |
        dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
        livingdoc test-assembly ${FILEPATH}/NameGeneratorTest.dll -t ${FILEPATH}/TestExecution.json
        mv LivingDoc.html TestReport_${GITHUB_RUN_NUMBER}.html
    - name: Publish Specflow Test Report
      uses: actions/upload-artifact@v2
      with:
        name: TestReport_${GITHUB_RUN_NUMBER}
        path: TestReport_${GITHUB_RUN_NUMBER}.html
