name: .NET Core

on:
  push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:
  BuildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - uses: cryptic-wizard/run-specflow-tests@v1.2.0
      with:
        test-assembly-path: RandomWordGeneratorTest/bin/Debug/netcoreapp3.1
        test-assembly-dll: RandomWordGeneratorTest.dll
        test-execution-json: TestExecution.json
        output-html: RandomWordGeneratorResults.html
        framework: netcoreapp3.1
        logger: trx
        logger-file-name: ../../RandomWordGeneratorResults.trx
    - uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Specflow Tests
        path: RandomWordGeneratorResults.trx
        reporter: dotnet-trx
    - name: Publish Specflow and TRX Test Report
      if: success() || failure()
      uses: actions/upload-artifact@v2
      with:
        name: RandomWordGeneratorTestResults
        path: |
          RandomWordGeneratorResults.html
          RandomWordGeneratorResults.trx