name: .NET Core

on:
  push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup .NET Core Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build Project
      run: dotnet build --no-restore
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
    - name: Install Specflow LivingDoc Tool
      run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
    - name: Generate Specflow Test Report
      env:
        FILEPATH: "NameGeneratorTest/bin/Debug/netcoreapp3.1"
      run: livingdoc test-assembly ${FILEPATH}/NameGeneratorTest.dll -t FILEPATH/TestExecution.json

    - name: Generate Timestamp
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
          timeZone: -5
          format: 'YYYY-MM-DD-HH-mm-ss'
    - name: Timestamp Specflow Test Report
      env:
        TIMESTAMP: "${{ steps.time.outputs.time }}"
      run: mv LivingDoc.html TestReport_$TIME.html
    - name: Publish Specflow Test Report
      env:
        TIMESTAMP: "${{ steps.time.outputs.time }}"
      uses: actions/upload-artifact@v2
      with:
        name: TestReport_$TIME
        path: TestReport.html
