name: .NET Core

on:
  push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
    - name: Install Specflow LivingDoc Tool
      run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
    - name: Generate Specflow Test Report
      run: livingdoc test-assembly NameGeneratorTest/bin/Debug/netcoreapp3.1/NameGeneratorTest.dll -t NameGeneratorTest/bin/Debug/netcoreapp3.1/TestExecution.json
    - name: Publish Test Report
      uses: actions/upload-artifact@v2
      with:
        name: TestReport.html
        path: LivingDoc.html
