name: NuGet

on:
  release:
    types:
      - created

jobs:
  Nuget:
    name: Nuget
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Setup DotnetCore
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Publish NuGet Package
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/cryptic-wizard/index.json" -n github -u cryptic-wizard -p ${{ secrets.NUGET_PUBLISH }} --store-password-in-clear-text
          dotnet pack RandomWordGenerator -c Release
          dotnet nuget push "RandomWordGenerator/bin/Release/RandomWordGenerator.0.9.0.nupkg" --source "github"